### ISSUE TITLE
Feature: Uploading gifs/bmps from web ui

### ISSUE THREAD

**Issue by DiverOfDark** [DiverOfDark/KNOMI#11]
That would simplify customization a lot and prevent requirement of reflashing knomi to just change visual esthetics.

**Comment by jMaddrell** [comment]
@DiverOfDark Would it make sense for configuring accent colours of text/ui elements to be added to the Theme page?

**Comment by DiverOfDark** [comment]
Certainly! Also I think that we need to store it on fs rather than on nvs - to be able to build selfcontained themes for upload.

**Comment by DiverOfDark** [comment]
After #53 only GIFs would be allowed.
