### ISSUE TITLE
KNOMI does not update on G28

### ISSUE THREAD

**Issue by selrahc13** [DiverOfDark/KNOMI#140]
Nothing happens when printer is running homing sequence - G28 macro status is empty using URL from API

Using Release 1.4.0 from November 22, 2023

**Comment by DiverOfDark** [comment]
Try use 2.0.0 (update both FW and Theme/Files) + include knomi.cfg from repository to your klipper config

**Comment by selrahc13** [comment]
I will try that and report back - thank you!
