### ISSUE TITLE
Help compiling: src/scenes/../network/WifiStation.h:14:51: error: no matching function for call to 'WiFiClass::begin(String, String)'

### ISSUE THREAD

**Issue by hdragoon** [DiverOfDark/KNOMI#159]
Hi, I got this error when compiling, what's the problem here?
![image](https://github.com/DiverOfDark/KNOMI/assets/62820191/3034da12-e664-4357-ac6b-9535798439e6)

**Comment by ducklingasa** [comment]
Hi @hdragoon,

I'm getting the same error as you. What was the solution?

Thanks!
