### ISSUE TITLE
knomi.cfg needs updating.

### ISSUE THREAD

**Issue by Brownbear1984** [DiverOfDark/KNOMI#160]
Found a couple of issues with the knomi.cfg file

1. Current versions of klipper now have Adaptive Bed Meshing without the need for Kamp (BED_MESH_CALIBRATE ADAPTIVE=1). The rename Macro doesn't pass the raw parameters to the renamed BTT_BED_MESH_CALIBRATE so the adaptive parameter is ignored. Updating the macro to include {rawparams} similar to the G28 macro resolves this 

```
[gcode_macro BED_MESH_CALIBRATE]
rename_existing: BTT_BED_MESH_CALIBRATE
gcode:
  SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=probing VALUE=True
  BTT_BED_MESH_CALIBRATE {rawparams}
  SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=probing VALUE=False
```
2. The Z_TILT_ADJUST macro could also do with a change since its adding a macro for Quad_Gantry_Level rather than renaming the existing Z_TILT_ADJUST
```
[gcode_macro Z_TILT_ADJUST]
rename_existing: BTT_Z_TILT_ADJUST
gcode:
  SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=qgling VALUE=True
  BTT_Z_TILT_ADJUST
  SET_GCODE_VARIABLE MACRO=_KNOMI_STATUS VARIABLE=qgling VALUE=False
```

**Comment by DiverOfDark** [comment]
Thank you!
I mostly took this knomi.cfg as-is from knomi v2 btt repo, but haven't thought much about it, as I personally use Voron 2.4 - so not using z_tilt / bed mesh.

I've raised the PR with changes you suggested.
