### ISSUE TITLE
KNOMI 2 support

### ISSUE THREAD

**Issue by DiverOfDark** [DiverOfDark/KNOMI#75]
BTT released KNOMI 2 with touchscreen and newer firmware:  https://github.com/bigtreetech/KNOMI/tree/firmware

Need adapt this firmware to update to KNOMI 2 + find missing features and port them.

As I don't own KNOMI 2 yet - I can't do this by myself.

**Comment by Bazeone** [comment]
I have a KNOMI 2 on it's way and i am willing to help. I do not know how to program, besides small python scripts and bash scripts.

**Comment by DiverOfDark** [comment]
Knomi V2 is supported starting from v2.2.0.
