### ISSUE TITLE
Automatic code formatter/linter

### ISSUE THREAD

**Issue by DiverOfDark** [DiverOfDark/KNOMI#9]
Currently during PRs we often see code being reformated by IDE - that makes reading PR harder.

We need to have some kind of autoformatter which would do code format on build + committed settings for this code formatter.

**Comment by jMaddrell** [comment]
I currently have format on save enabled in VS Code with clangFormat and LLVM Style. I'm happy to change this.

**Comment by DiverOfDark** [comment]
Can you share any kind of readme on how to use it?
I'm coming from java/c# world and not familiar with best practices on cpp - so I'll stick to whatever in community already exists.

Also - is it possible to trigger it from CLI? I still want to use CLion trial (and beg JB to get a license for OSS project) - so ideally we'll have a pre-build script which would autoformat code both on cpp part and on svelte/ts part.

**Comment by jMaddrell** [comment]
I just did brew-install clang-format and then set VSCode up like this:
<img width="842" alt="image" src="https://github.com/DiverOfDark/KNOMI/assets/12979795/462bd56c-4953-4f25-896f-2e76bc28f75a">

I have tried CLion previously and from a quick google it also supports clang-format: https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html

**Comment by jMaddrell** [comment]
To run from the CLI something like this would do the entire project:
```sh
clang-format src/**/*.h -i && clang-format src/**/*.cpp -I
```

**Comment by jMaddrell** [comment]
We could also use https://pre-commit.com/hooks.html with the clang-format extension: https://github.com/pre-commit/mirrors-clang-format
